/**
 * @Author: Eduardo Santos
 * @Date:   2023-10-05 21:18:26
 * @Last Modified by:   Eduardo Santos
 * @Last Modified time: 2023-10-09 16:05:34
 */
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'relatorio',
    'portefolio',
    //'intro',
    ////'hello',
    //{
    //  type: 'category',
    //  label: 'Tutorial Basics',
    //  items: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
    //},
    //{
    //  type: 'category',
    //  label: 'Tutorial Extras',
    //  items: [{ type: 'autogenerated', dirName: 'tutorial-extras' }],
    //}
  ],

};

module.exports = sidebars;
